### PR TITLE
Add typescript typing

### PR DESCRIPTION
**Pull request by hoetmaaiers**
Thank you for this react-leaflet version 2 supporting plugin. I wanted to add some typescript typing to the project.

### CODE REVIEW

**Comment by hoetmaaiers** [comment]
Any feedback or chance of approving this PR?

**Comment by r3mi** [comment]
Hello, yes, it would be nice to have the typings integrated. Thanks for the component 👍 

@hoetmaaiers you are missing some props e.g. `className`. See [options for DumbControl](https://github.com/LiveBy/react-leaflet-control/blob/master/lib/control.jsx#L6) if I am not mistaken.
Also you don't need to type `children` normally ?

**Comment by hoetmaaiers** [comment]
Hi @r3mi , thank you for the suggestions. When any of the people responsible for merging this PR would respond, I would be very happy to apply your feedback.

**Comment by jgimbel** [comment]
Sorry it took so long to get around to this. react-leaflet-control@2.1.2 has been published with types

**Pull request merged**
